name: Windows Build & Tests

on:
  push:
    branches:
      - master

jobs:
  build_windows_msvc:
    name: Build Windows | MSVC
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_config: [Release, Debug]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Generate Project
        run: cmake -B Build/${{ matrix.build_config }} -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} -G "Visual Studio 16 2019" -A x64

      - name: Build DynamicLibraryTest
        run: cmake --build Build/${{ matrix.build_config }} --config ${{ matrix.build_config }} --verbose

      - name: Run Tests
        run: cd Build/${{ matrix.build_config }} && ctest -C ${{ matrix.build_config }} -V